第一章 序列和元组

In [ ]:
s1=[1,2,3]
s2=('4','5','6')
s3='789'

a3=3
print(s1*a3,s2*a3,s3*a3)

In [ ]:
t1=('a','b','c')
t2=['4','5','6']
print(t1.count('a'))
print(t1.count('b'))
print(t2.index('6',1))
print(t2.index('5',1,2))
print(t2.index('6',1,2))

In [ ]:
s1=('甲','乙','丙','丁')
print(s1[0:3])
s2=('戊',)
print(s1+s2)
#del(s1)
print(s1*1)

第二章 集合类型

In [5]:
num={1,2,3,4}
dempty={}
sEmpty=set()#创建空集合时不能使用’{}'
double=set('23468')
word=set(['apple','pear','banana'])
word1=set(('apple','pear','banana'))
print(type(num), num)
print(sEmpty)
print(type(dempty), dempty)
print(double)
print(word)
print(word1)

s=str(word)
t=tuple(word)
l=list(word)
print(s,type(s))
print(t)
print(l)

<class 'set'> {1, 2, 3, 4}
set()
<class 'dict'> {}
{'4', '8', '3', '2', '6'}
{'pear', 'apple', 'banana'}
{'pear', 'apple', 'banana'}
{'pear', 'apple', 'banana'} <class 'str'>
('pear', 'apple', 'banana')
['pear', 'apple', 'banana']


In [6]:
a={1,2,3,4}
b={4,5,6,7}
print(a|b,a,b)
print(a.union(b),a,b)
a|=b
print(a,b)
c =[1,1,2]
print(c.remove(1),c)

{1, 2, 3, 4, 5, 6, 7} {1, 2, 3, 4} {4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7} {1, 2, 3, 4} {4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7} {4, 5, 6, 7}
None [1, 2]


In [7]:
a={1,2,3,4}
b = a
c=a.copy()

print(a,b,c)
print(id(a),id(b),id(c))
a.pop()
print(a,b,c)

{1, 2, 3, 4} {1, 2, 3, 4} {1, 2, 3, 4}
1693914371680 1693914371680 1693914370560
{2, 3, 4} {2, 3, 4} {1, 2, 3, 4}


第三章 字典类型

In [9]:
poet={'李白':'山阴之秋','杜甫':'江南','杜牧':'西江月','白居易':'菩萨蛮'}
for i in poet:
    print(i,poet.get(i))
print('-'*20)
for i in poet.values():
    print(i)  
print('-'*20)
for i in poet.keys():
    print(i) 
print('-'*20)
for i in poet.items():
    print(i) 
print('李白'in poet)
print('李白'in poet.keys())
print('江南'in poet.values())
print(('杜甫','江南') in poet.items())
    
#字典的排序
poet={'李白':'山阴之秋','杜甫':'江南','杜牧':'西江月','白居易':'菩萨蛮'}
print(sorted(poet.items(),key=lambda x:x[0]))
x=len(poet)
for i in range(x):
    poet.popitem()
    print(poet)    
    



李白 山阴之秋
杜甫 江南
杜牧 西江月
白居易 菩萨蛮
--------------------
山阴之秋
江南
西江月
菩萨蛮
--------------------
李白
杜甫
杜牧
白居易
--------------------
('李白', '山阴之秋')
('杜甫', '江南')
('杜牧', '西江月')
('白居易', '菩萨蛮')
True
True
True
True
[('李白', '山阴之秋'), ('杜牧', '西江月'), ('杜甫', '江南'), ('白居易', '菩萨蛮')]
{'李白': '山阴之秋', '杜甫': '江南', '杜牧': '西江月'}
{'李白': '山阴之秋', '杜甫': '江南'}
{'李白': '山阴之秋'}
{}


第四章 数据维度

第五章 一维数据处理

In [ ]:
a='98,78,84,72,93,95'
a = a.split(',')
print(a)
b='、'.join(a)
print(b)
# f =open('python等级考试三级','w')
# f.write(b)
# f.close()



第六章 二维数据处理

In [ ]:
message2=[
    ['姓名','年龄','身高','体重','分数'],
    ['李志雨','20','184','65','9'],
    ['王家益','19','165','5.1','9.5'],
    ['李恒涛','21','175','68','8.8']
]
f=open('考试信息.csv','w')
for i in message2:
    f.write(','.join(i)+'\n')
f.close()    
    
ls1=[]
f=open('考试信息.csv','r')
for i in f:
    l=  i.strip().split(',')
    ls1.append(l)
f.close()
print(ls1)

import csv
f=open('考试信息.csv','r')
reader=csv.DictReader(f)
for i in reader:
    print(i)
f.close()

In [11]:
import csv
message2=[
    ['姓名','年龄','身高','体重','分数'],
    ['李志雨','20','184','65','9'],
    ['王家益','19','165','5.1','9.5'],
    ['李恒涛','21','175','68','8.8']
]
f=open('城市人口.csv','w',newline='')
writer=csv.writer(f)
writer.writerows(message2)
f.close()

f=open('城市人口.csv','r')
reader=csv.reader(f)
for i in reader:
    if not i: 
        print(i)
        continue 
    print(i[3])
f.close()




体重
65
5.1
68


第七章 高维数据处理

In [12]:
import json
l1=['apple','pear','banana']
j0=json.dumps(l1)
print(j0,type(j0))

["apple", "pear", "banana"] <class 'str'>


第八章 文本处理

In [13]:
import re 
dn=r'\d{3}'
a=re.match(dn,'123木头人')
b=re.match(dn,'木头人123')
c=re.search(dn,'木头人123')
print(a,b,c)
s='Stphen William Hawking, physicist'
m=re.match(r'(\w+) (\w+) (\w+)',s)
n=re.match(r'\w+ \w+ \w+',s)
print(m,m.groups())
print(n,n.groups())

prog=re.compile('[^a-zA-Z]')#匹配非字母
sentence='Stphen William Hawking, physicist.爱屋及乌'
result=re.findall(prog,sentence)
print(result)

w='Wooow, you are so cute!'
t=re.split(r'\W{2}',w)
print(t)

<re.Match object; span=(0, 3), match='123'> None <re.Match object; span=(3, 6), match='123'>
<re.Match object; span=(0, 22), match='Stphen William Hawking'> ('Stphen', 'William', 'Hawking')
<re.Match object; span=(0, 22), match='Stphen William Hawking'> ()
[' ', ' ', ',', ' ', '.', '爱', '屋', '及', '乌']
['Wooow', 'you are so cute!']


第九章 数据爬取

第十章 HTML数据

In [ ]:
import requests
from bs4 import BeautifulSoup
r=requests.get('http://www.baidu.com')
r.encoding='utf-8'
soup=BeautifulSoup(r.text,features='html.parser')
print(soup.title)
print(soup.img)

for i in soup.find_all('body'):
    for c in (i.children):
        print(c.name)

第十一章 向量数据

In [14]:
import numpy as np
a=np.random.randn(4,3,2)
print(a)
print("*"*20)
print(np.max(a,axis=0))
print("*"*20)
print(np.max(a,axis=1))
print("*"*20)
print(np.max(a,axis=2))
print("*"*20)
print(np.max(a))

o1=np.zeros((2,3))
o2=np.ones((2,1))
oo=np.concatenate((o1,o2),axis=1)
# oo = o1+o2
# print(o1)
# print(o2)
# print(oo,oo.shape)

[[[-1.07217206 -0.53904968]
  [-0.40535791 -0.32027094]
  [ 2.75584023 -1.51453267]]

 [[-0.34139405 -0.23416474]
  [-0.88908869  0.18041436]
  [-1.25517151  1.15468054]]

 [[ 0.11199207 -1.45540736]
  [-0.55457455  0.32573902]
  [-0.43769225  0.64882359]]

 [[ 0.63108675 -0.67689004]
  [-0.07856     0.11109993]
  [ 1.70052142  0.58918963]]]
********************
[[ 0.63108675 -0.23416474]
 [-0.07856     0.32573902]
 [ 2.75584023  1.15468054]]
********************
[[ 2.75584023 -0.32027094]
 [-0.34139405  1.15468054]
 [ 0.11199207  0.64882359]
 [ 1.70052142  0.58918963]]
********************
[[-0.53904968 -0.32027094  2.75584023]
 [-0.23416474  0.18041436  1.15468054]
 [ 0.11199207  0.32573902  0.64882359]
 [ 0.63108675  0.11109993  1.70052142]]
********************
2.7558402328936658


第十二章 图形数据

In [ ]:
from PIL import Image
from PIL import ImageEnhance
from PIL import ImageFilter
Im=Image.open('1.jpg')
im2=Im.filter(ImageFilter.EMBOSS)
im3=Im.crop((200,60,470,350))
im3.show()
#Im.show()
# im2=ImageEnhance.Color(Im)
# im2=ImageEnhance.Contrast(Im)
# im3=im2.enhance(10)
# im3.show()

In [ ]:
a=int(input('s'))

b=0
for i in range(10): 
    if a==1.0:
        print(b)
    if a%2!=0:
        a=a*3+1
    a/2
    b+1    
print(a)
    