第一章 序列和元组

In [1]:
s1=[1,2,3]
s2=('4','5','6')
s3='789'

a3=3
print(s1*a3,s2*a3,s3*a3)

[1, 2, 3, 1, 2, 3, 1, 2, 3] ('4', '5', '6', '4', '5', '6', '4', '5', '6') 789789789


In [7]:
t1=('a','b','c')
t2=['4','5','6']
print(t1.count('a'))
print(t1.count('b'))
print(t2.index('6',1))
print(t2.index('5',1,2))
print(t2.index('6',1,2))

1
1
2
1


ValueError: '6' is not in list

In [8]:
s1=('甲','乙','丙','丁')
print(s1[0:3])
s2=('戊',)
print(s1+s2)
#del(s1)
print(s1*2)

('甲', '乙', '丙')
('甲', '乙', '丙', '丁', '戊')
('甲', '乙', '丙', '丁', '甲', '乙', '丙', '丁')


第二章 集合类型

In [10]:
num={1,2,3,4}
dempty={}
sEmpty=set()#创建空集合时不能使用’{}'
double=set('23468')
word=set(['apple','pear','banana'])
word1=set(('apple','pear','banana'))
print(type(num), num)
print(type(dempty), dempty)
print(sEmpty)
print(double)
print(word)
print(word1)

s=str(word)##
t=tuple(word)
l=list(word)
print(s,type(s))
print(t)
print(l)

<class 'set'> {1, 2, 3, 4}
<class 'dict'> {}
set()
{'2', '3', '6', '8', '4'}
{'banana', 'apple', 'pear'}
{'banana', 'apple', 'pear'}
{'banana', 'apple', 'pear'} <class 'str'>
('banana', 'apple', 'pear')
['banana', 'apple', 'pear']


In [6]:
a={1,2,3,4}
b={4,5,6,7}
print(a|b,a,b)
print(a.union(b),a,b)
a|=b
print(a,b)
c =[1,1,2]
print(c.remove(1),c)

{1, 2, 3, 4, 5, 6, 7} {1, 2, 3, 4} {4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7} {1, 2, 3, 4} {4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7} {4, 5, 6, 7}
None [1, 2]


In [14]:
a={1,2,3,4}
b = a
c=a.copy()

print(a,b,c)
print(id(a),id(b),id(c))
a.pop()
print(a,b,c)

{1, 2, 3, 4} {1, 2, 3, 4} {1, 2, 3, 4}
2474281367584 2474281367584 2474281368032
{2, 3, 4} {2, 3, 4} {1, 2, 3, 4}


第三章 字典类型

In [15]:
poet={'李白':'山阴之秋','杜甫':'江南','杜牧':'西江月','白居易':'菩萨蛮'}
for i in poet:
    print(i,poet.get(i))
print('-'*20)
for i in poet.values():
    print(i)  
print('-'*20)
for i in poet.keys():
    print(i) 
print('-'*20)
for i in poet.items():
    print(i) 
print('李白'in poet)
print('李白'in poet.keys())
print('江南'in poet.values())
print(('杜甫','江南') in poet.items())
    
#字典的排序
poet={'李白':'山阴之秋','杜甫':'江南','杜牧':'西江月','白居易':'菩萨蛮'}
print(sorted(poet.items(),key=lambda x:x[0]))
poet['李白'] = "k"
x=len(poet)
for i in range(x):
    poet.popitem()
    print(poet)    
    



李白 山阴之秋
杜甫 江南
杜牧 西江月
白居易 菩萨蛮
--------------------
山阴之秋
江南
西江月
菩萨蛮
--------------------
李白
杜甫
杜牧
白居易
--------------------
('李白', '山阴之秋')
('杜甫', '江南')
('杜牧', '西江月')
('白居易', '菩萨蛮')
True
True
True
True
[('李白', '山阴之秋'), ('杜牧', '西江月'), ('杜甫', '江南'), ('白居易', '菩萨蛮')]
{'李白': 'k', '杜甫': '江南', '杜牧': '西江月'}
{'李白': 'k', '杜甫': '江南'}
{'李白': 'k'}
{}


第四章 数据维度

第五章 一维数据处理

In [6]:
a='98,78,84,72,93,95'
a = a.split(',')
print(a)
b='、'.join(a)
print(b)
# f =open('python等级考试三级','w')
# f.write(b)
# f.close()



['98', '78', '84', '72', '93', '95']
98、78、84、72、93、95


第六章 二维数据处理

In [16]:
message2=[
    ['姓名','年龄','身高','体重','分数'],
    ['李志雨','20','184','65','9'],
    ['王家益','19','165','5.1','9.5'],
    ['李恒涛','21','175','68','8.8']
]
f=open('考试信息.csv','w')
for i in message2:
    f.write(','.join(i)+'\n')
f.close()    
    
ls1=[]
f=open('考试信息.csv','r')
for i in f:
    l=  i.strip().split(',')
    ls1.append(l)
f.close()
print(ls1)

import csv
f=open('考试信息.csv','r')
reader=csv.DictReader(f)
for i in reader:
    print(i)
f.close()

[['姓名', '年龄', '身高', '体重', '分数'], ['李志雨', '20', '184', '65', '9'], ['王家益', '19', '165', '5.1', '9.5'], ['李恒涛', '21', '175', '68', '8.8']]
{'姓名': '李志雨', '年龄': '20', '身高': '184', '体重': '65', '分数': '9'}
{'姓名': '王家益', '年龄': '19', '身高': '165', '体重': '5.1', '分数': '9.5'}
{'姓名': '李恒涛', '年龄': '21', '身高': '175', '体重': '68', '分数': '8.8'}


In [11]:
import csv
message2=[
    ['姓名','年龄','身高','体重','分数'],
    ['李志雨','20','184','65','9'],
    ['王家益','19','165','5.1','9.5'],
    ['李恒涛','21','175','68','8.8']
]
f=open('城市人口.csv','w',newline='')
writer=csv.writer(f)
writer.writerows(message2)
f.close()

f=open('城市人口.csv','r')
reader=csv.reader(f)
for i in reader:
    if not i: 
        print(i)
        continue 
    print(i[3])
f.close()




体重
65
5.1
68


第七章 高维数据处理

In [12]:
import json
l1=['apple','pear','banana']
j0=json.dumps(l1)
print(j0,type(j0))

["apple", "pear", "banana"] <class 'str'>


第八章 文本处理

In [18]:
'''正则表达式实例
字符匹配
实例	    描述
python	    匹配 "python".
字符类
实例	     描述
[Pp]ython	匹配 "Python" 或 "python"
rub[ye]	    匹配 "ruby" 或 "rube"
[aeiou]	    匹配中括号内的任意一个字母
[0-9]	    匹配任何数字。类似于 [0123456789]
[a-z]	    匹配任何小写字母
[A-Z]	    匹配任何大写字母
[a-zA-Z0-9]	匹配任何字母及数字
[^aeiou]	除了aeiou字母以外的所有字符
[^0-9]	    匹配除了数字外的字符
特殊字符类
实例	     描述
.	        匹配除 "\n" 之外的任何单个字符。要匹配包括 '\n' 在内的任何字符，请使用象 '[.\n]' 的模式。
\d	        匹配一个数字字符。等价于 [0-9]。
\D	        匹配一个非数字字符。等价于 [^0-9]。
\s	        匹配任何空白字符，包括空格、制表符、换页符等等。等价于 [ \f\n\r\t\v]。
\S	        [^ \f\n\r\t\v]。
\w	        匹配包括下划线的任何单词字符。等价于'[A-Za-z0-9_]'。
\W	        匹配任何非单词字符。等价于 '[^A-Za-z0-9_]'。



模式	描述
^	匹配字符串的开头
$	匹配字符串的末尾。
.	匹配任意字符，除了换行符，当re.DOTALL标记被指定时，则可以匹配包括换行符的任意字符。
[...]	用来表示一组字符,单独列出：[amk] 匹配 'a'，'m'或'k'
[^...]	不在[]中的字符：[^abc] 匹配除了a,b,c之外的字符。
re*	匹配0个或多个的表达式。
re+	匹配1个或多个的表达式。
re?	匹配0个或1个由前面的正则表达式定义的片段，非贪婪方式
re{ n}	 
re{ n,}	精确匹配n个前面表达式。
re{ n, m}	匹配 n 到 m 次由前面的正则表达式定义的片段，贪婪方式
a| b	匹配a或b
(re)	G匹配括号内的表达式，也表示一个组
(?imx)	正则表达式包含三种可选标志：i, m, 或 x 。只影响括号中的区域。
(?-imx)	正则表达式关闭 i, m, 或 x 可选标志。只影响括号中的区域。
(?: re)	类似 (...), 但是不表示一个组
(?imx: re)	在括号中使用i, m, 或 x 可选标志
(?-imx: re)	在括号中不使用i, m, 或 x 可选标志
(?#...)	注释.
(?= re)	前向肯定界定符。如果所含正则表达式，以 ... 表示，在当前位置成功匹配时成功，否则失败。但一旦所含表达式已经尝试，匹配引擎根本没有提高；模式的剩余部分还要尝试界定符的右边。
(?! re)	前向否定界定符。与肯定界定符相反；当所含表达式不能在字符串当前位置匹配时成功
(?> re)	匹配的独立模式，省去回溯。
\w	匹配字母数字
\W	匹配非字母数字
\s	匹配任意空白字符，等价于 [\t\n\r\f].
\S	匹配任意非空字符
\d	匹配任意数字，等价于 [0-9].
\D	匹配任意非数字
\A	匹配字符串开始
\Z	匹配字符串结束，如果是存在换行，只匹配到换行前的结束字符串。c
\z	匹配字符串结束
\G	匹配最后匹配完成的位置。
\b	匹配一个单词边界，也就是指单词和空格间的位置。例如， 'er\b' 可以匹配"never" 中的 'er'，但不能匹配 "verb" 中的 'er'。
\B	匹配非单词边界。'er\B' 能匹配 "verb" 中的 'er'，但不能匹配 "never" 中的 'er'。
\n, \t, 等.	匹配一个换行符。匹配一个制表符。等
\1...\9	匹配第n个分组的子表达式。
\10	匹配第n个分组的子表达式，如果它经匹配。否则指的是八进制字符码的表达式
'''

import re 
dn=r'\d{3}'
a=re.match(dn,'0123木头人')
b=re.match(dn,'木头人123')
c=re.search(dn,'木头人0123')
print(a,b,c)

s='Stphen William Hawking, physicist'
m=re.match(r'(\w+) (\w+) (\w+)',s)
n=re.match(r'\w+ \w+ \w+',s)
print(m,m.groups())
print(n,n.groups())

prog=re.compile('[^a-zA-Z]')#匹配非字母
sentence='Stphen William Hawking, physicist.爱屋及乌'
result=re.findall(prog,sentence)
print(result)

w='Wooow, you are so cute!'
t=re.split(r'\W{2}',w)
print(t)

<re.Match object; span=(0, 3), match='012'> None <re.Match object; span=(3, 6), match='012'>
<re.Match object; span=(0, 22), match='Stphen William Hawking'> ('Stphen', 'William', 'Hawking')
<re.Match object; span=(0, 22), match='Stphen William Hawking'> ()
[' ', ' ', ',', ' ', '.', '爱', '屋', '及', '乌']
['Wooow', 'you are so cute!']


第九章 数据爬取

第十章 HTML数据

In [19]:
import requests
from bs4 import BeautifulSoup
r=requests.get('http://www.baidu.com')
r.encoding='utf-8'
soup=BeautifulSoup(r.text,features='html.parser')
print(soup.title)
print(soup.img)

for i in soup.find_all('body'):
    for c in (i.children):
        print(c.name)

<title>百度一下，你就知道</title>
<img height="129" hidefocus="true" src="//www.baidu.com/img/bd_logo1.png" width="270"/>
None
div
None


第十一章 向量数据

In [20]:
import numpy as np
a=np.random.randn(4,3,2)
print(a)
print("*"*20)
print(np.max(a,axis=0))
print("*"*20)
print(np.max(a,axis=1))
print("*"*20)
print(np.max(a,axis=2))
print("*"*20)
print(np.max(a))

o1=np.zeros((2,3))
o2=np.ones((2,1))
oo=np.concatenate((o1,o2),axis=1)
# oo = o1+o2
print(o1)
print(o2)
print(oo,oo.shape)

[[[ 1.82196741 -0.87701453]
  [ 0.77479499 -0.73294829]
  [-0.21812224 -0.07760365]]

 [[-0.08444392  0.64897603]
  [ 1.05813246 -0.38479965]
  [ 1.20449951  0.30732903]]

 [[ 0.24096588 -0.21070922]
  [ 0.50449313 -0.67393034]
  [ 1.15433096 -0.58265578]]

 [[ 1.32155975 -1.2367481 ]
  [-0.96470751 -0.09255401]
  [ 0.36092623  1.82482056]]]
********************
[[ 1.82196741  0.64897603]
 [ 1.05813246 -0.09255401]
 [ 1.20449951  1.82482056]]
********************
[[ 1.82196741 -0.07760365]
 [ 1.20449951  0.64897603]
 [ 1.15433096 -0.21070922]
 [ 1.32155975  1.82482056]]
********************
[[ 1.82196741  0.77479499 -0.07760365]
 [ 0.64897603  1.05813246  1.20449951]
 [ 0.24096588  0.50449313  1.15433096]
 [ 1.32155975 -0.09255401  1.82482056]]
********************
1.8248205550751118
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]]
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]] (2, 4)


第十二章 图形数据

In [22]:
from PIL import Image
from PIL import ImageEnhance
from PIL import ImageFilter
Im=Image.open('1.jpg')
im2=Im.filter(ImageFilter.EMBOSS)
im3=Im.crop((200,60,470,350))
im3.show()
Im.show()
# im2=ImageEnhance.Color(Im)
# im2=ImageEnhance.Contrast(Im)
# im3=im2.enhance(10)
# im3.show()

In [ ]:
a=int(input('s'))

b=0
for i in range(10): 
    if a==1.0:
        print(b)
    if a%2!=0:
        a=a*3+1
    a/2
    b+1    
print(a)
    